[workspace]
members = ["fts-core", "fts-demo", "fts-server", "fts-solver"]
resolver = "2"

[workspace.package]
authors = ["Jason Dark <jason.dark@forwardmarketdesign.com>", "Fabio Isler <fabio.isler@forwardmarketdesign.com>"]
edition = "2024"
license = "MIT"
publish = false
rust-version = "1.85"
version = "0.1.0"

[workspace.dependencies]
clap = "4.5"
fxhash = "0.2"
humantime = "2.1"
indexmap = "2.8"
rstest = { version = "0.25", default-features = false }
rstest_reuse = "0.7"
serde = "1.0"
serde_json = "1.0"
thiserror = "2.0"
time = "0.3"
tokio = "1.44"
tracing = "0.1"
utoipa = "5.3"
uuid = "1.16"
