# fly.toml app configuration file generated for fts-demo on 2025-04-04T10:01:30+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fts-demo'
primary_region = 'bos'

[build]

[deploy]
wait_timeout = "1m"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  
  [[http_service.checks]]
    grace_period = "5s"
    interval = "30s"
    timeout = "5s"
    path = "/healthsss"

[env]
  API_PORT = "8080"
  TRADE_RATE = "1h"

[processes]
  app = "--api-secret ${DEMO_API_SECRET}"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
